### ISSUE TITLE
Glyphs 3: Does not stay on

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/ShowAngledHandles#20]
Plug-in loads in G3, but stays active only until something happens, e.g., you move your mouse over a point and it highlights.

@schriftgestalt to the rescue

**Comment by LibertyType** [comment]
That is not what I'm seeing. 
1. I can activate it in the Font Window and it stays activated. If I open a glyph, it deactivates.
2. If I attempt to activate it in a glyph window, it turns blue for less than a second, then deactivates.
I discovered the #1 occurrence after I first reported it in the Beta thread. It is the app that is causing it.

**Comment by schriftgestalt** [comment]
The deactivation is a measure build in Glyphs to avoid a broken reporter plugin run crazy. So if there is an uncouth exception, it is deactivated.

**Comment by schriftgestalt** [comment]
fixed

**Comment by LibertyType** [comment]
macOS 10.13.6 -- Sorry, but I'm still seeing the same behavior, the momentary activation then immediate deactivation. I tried removing all other plugins, but nothing changed. I tried reinstalling, both through Plugin Manager and also manually. Still the same.

**Comment by schriftgestalt** [comment]
I fixed the code. Rainer needs to build a new binary.
